name = "nikepig/contracts"
version = "0.1.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "NikePig - Perpetual High-Stakes Lottery dApp Smart Contracts on Cardano"

[repository]
user = "nikepig"
project = "contracts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
